### Figure 17

In [1]:
import numpy as np
import scipy

In [1]:
#dir(np)

In [3]:
list = [0, 1, 2]

In [4]:
list[1]

1

In [2]:
#dir(list)

In [6]:
list.append(3)

In [7]:
list

[0, 1, 2, 3]

In [8]:
for number in list:
    if number >= 1:
        print("oh my god!")
    else:
        print("cool!")

cool!
oh my god!
oh my god!
oh my god!


In [9]:
list.append(4)

In [10]:
list

[0, 1, 2, 3, 4]

In [11]:
for list[-1] in list:
    list.append()

TypeError: append() takes exactly one argument (0 given)

In [ ]:
A = [
    [1,2],[4,6],[9,5]
]

In [ ]:
U,S,V = np.linalg.svd(A)

In [ ]:
U

In [ ]:
S

In [12]:
V

NameError: name 'V' is not defined

In [13]:
import numpy as np
import scipy
import matplotlib.pyplot as plt
import astropy
from astropy.io import fits

In [14]:
file = ('/users/mirandaviederman/Downloads/FITS Files/N_data/apStar-r8-2M05580827+1345138.fits')

In [15]:
file

'/users/mirandaviederman/Downloads/FITS Files/N_data/apStar-r8-2M05580827+1345138.fits'

In [16]:
file2 = ('/users/mirandaviederman/Downloads/FITS Files/N_data/apStar-r8-2M08463782+5729103.fits')

In [17]:
file2

'/users/mirandaviederman/Downloads/FITS Files/N_data/apStar-r8-2M08463782+5729103.fits'

In [18]:
fits.open(file)

[<astropy.io.fits.hdu.image.PrimaryHDU object at 0x106264c18>, <astropy.io.fits.hdu.image.ImageHDU object at 0x1062cba20>, <astropy.io.fits.hdu.image.ImageHDU object at 0x1062cbdd8>, <astropy.io.fits.hdu.image.ImageHDU object at 0x1062d2898>, <astropy.io.fits.hdu.image.ImageHDU object at 0x1062d2fd0>, <astropy.io.fits.hdu.image.ImageHDU object at 0x1062d7748>, <astropy.io.fits.hdu.image.ImageHDU object at 0x1062d7e80>, <astropy.io.fits.hdu.image.ImageHDU object at 0x1062dd5f8>, <astropy.io.fits.hdu.image.ImageHDU object at 0x1062ddd68>, <astropy.io.fits.hdu.table.BinTableHDU object at 0x1062ea940>]

In [19]:
fits.open(file2)

[<astropy.io.fits.hdu.image.PrimaryHDU object at 0x10697c550>, <astropy.io.fits.hdu.image.ImageHDU object at 0x106983668>, <astropy.io.fits.hdu.image.ImageHDU object at 0x106983da0>, <astropy.io.fits.hdu.image.ImageHDU object at 0x106989518>, <astropy.io.fits.hdu.image.ImageHDU object at 0x106989c50>, <astropy.io.fits.hdu.image.ImageHDU object at 0x10698d3c8>, <astropy.io.fits.hdu.image.ImageHDU object at 0x10698db00>, <astropy.io.fits.hdu.image.ImageHDU object at 0x10698def0>, <astropy.io.fits.hdu.image.ImageHDU object at 0x1069939e8>, <astropy.io.fits.hdu.table.BinTableHDU object at 0x10699d5c0>]

In [20]:
file_info = fits.open(file)

In [21]:
file2_info = fits.open(file2)

In [22]:
file_info.info()

Filename: /users/mirandaviederman/Downloads/FITS Files/N_data/apStar-r8-2M05580827+1345138.fits
No.    Name      Ver    Type      Cards   Dimensions   Format
  0  PRIMARY       1 PrimaryHDU     215   ()      
  1                1 ImageHDU        13   (8575, 8)   float32   
  2                1 ImageHDU        13   (8575, 8)   float32   
  3                1 ImageHDU        13   (8575, 8)   int16   
  4                1 ImageHDU        13   (8575, 8)   float32   
  5                1 ImageHDU        13   (8575, 8)   float32   
  6                1 ImageHDU        13   (8575, 8)   float32   
  7                1 ImageHDU        13   (8575, 8)   float32   
  8                1 ImageHDU        29   (26,)   float64   
  9                1 BinTableHDU     90   1R x 33C   [180A, 6I, 24A, 6J, 6I, 6D, 6E, 6E, 6E, 6E, 2I, 2E, 2E, 2E, 2E, E, E, E, E, E, 6E, 6E, 6E, 6E, 6E, 6E, 6E, 3208E, 3208E, 401E, D, D, 401E]   


In [23]:
file2_info.info()

Filename: /users/mirandaviederman/Downloads/FITS Files/N_data/apStar-r8-2M08463782+5729103.fits
No.    Name      Ver    Type      Cards   Dimensions   Format
  0  PRIMARY       1 PrimaryHDU     139   ()      
  1                1 ImageHDU        13   (8575, 4)   float32   
  2                1 ImageHDU        13   (8575, 4)   float32   
  3                1 ImageHDU        13   (8575, 4)   int16   
  4                1 ImageHDU        13   (8575, 4)   float32   
  5                1 ImageHDU        13   (8575, 4)   float32   
  6                1 ImageHDU        13   (8575, 4)   float32   
  7                1 ImageHDU        13   (8575, 4)   float32   
  8                1 ImageHDU        29   (26,)   float64   
  9                1 BinTableHDU     90   1R x 33C   [62A, 2I, 10A, 2J, 2I, 2D, 2E, 2E, 2E, 2E, 2I, 2E, 2E, 2E, 2E, E, E, E, E, E, 2E, 2E, 2E, 2E, 2E, 2E, 2E, 1604E, 1604E, 401E, D, D, 401E]   


In [24]:
file_info[1].data.shape

(8, 8575)

In [25]:
file2_info[1].data.shape

(4, 8575)

In [26]:
data = file_info[1].data

In [27]:
data

array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]], dtype=float32)

In [28]:
data.shape

(8, 8575)

In [29]:
data2 = file2_info[1].data

In [30]:
data

array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]], dtype=float32)

In [31]:
data2.shape

(4, 8575)

In [32]:
type(data)

numpy.ndarray

In [37]:
type(data2)

numpy.ndarray

In [38]:
np.vstack((data,data2))

array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]], dtype=float32)

In [41]:
vstack = np.vstack((data,data2))

In [42]:
vstack.shape

(12, 8575)